<a href="https://colab.research.google.com/github/Nimo160302/Deep_Learning_Codes/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch
import tensorflow as tf


Task 1 (5 Marks) – TensorFlow (Keras backend):
Manually initialize weights and bias using tf.Variable

Compute z = XW + b using tf.matmul

Apply sigmoid using tf.math.sigmoid

Compute Binary Cross-Entropy manually:

In [ ]:
x =   tf.constant(tf.random.uniform(shape  =  [1,3]))

In [ ]:
w  = tf.Variable(tf.random.uniform(shape  =  [3,1]))

In [ ]:
b = tf.Variable([1.0])

In [ ]:
#ForwardPass
z  =  tf.matmul(x, w)  + b
y_pred =  tf.math.sigmoid(z)

In [ ]:
def binary_cross(y_pred, y_true):
  return -1* (y_pred * tf.math.log(y_true + 1e-8) + (1-y_pred ) * tf.math.log(1-y_true+1e-8))

In [ ]:
y_true =  tf.constant([[1.0]])
loss = binary_cross(y_pred, y_true)

In [ ]:
loss

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.6999307]], dtype=float32)>

Task 2 (5 Marks) – PyTorch:
Manually initialize weights and bias using torch.tensor

Compute z = XW + b using torch.mm

Apply sigmoid using torch.sigmoid

Compute the same binary cross-entropy manually

Call .backward() and print gradients of weights



In [ ]:
torch.manual_seed(42)
x  =  torch.tensor(torch.rand(size  = [1,3]))

<ipython-input-10-7d1fa72f0583>:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x  =  torch.tensor(torch.rand(size  = [1,3]))


In [ ]:
w =  torch.nn.Parameter(torch.tensor(torch.rand(size  = [3,1])))

<ipython-input-11-31751d9d24c1>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  w =  torch.nn.Parameter(torch.tensor(torch.rand(size  = [3,1])))


In [ ]:
b  = torch.nn.Parameter(torch.tensor([1.0]))

In [ ]:
w

Parameter containing:
tensor([[0.9593],
        [0.3904],
        [0.6009]], requires_grad=True)

In [ ]:
b

Parameter containing:
tensor([1.], requires_grad=True)

In [ ]:
z =  torch.mm(x,w) +  b
y_pred  =  torch.sigmoid(z)
y_true = torch.tensor([[1.0]])


In [ ]:
loss  = -1* (y_true * torch.log(y_pred + 1e-8) + (1-y_true) * torch.log(1-y_pred + 1e-8))

In [ ]:
# Make the loss a scalar by summing it
loss_scalar = loss.sum()

In [ ]:
loss_scalar.backward()

In [ ]:
print(w.grad)

tensor([[-0.0711],
        [-0.0738],
        [-0.0309]])


In [ ]:
!jupyter nbconvert --to html /content/25DLS304_NimishParmar.ipynb

[NbConvertApp] Converting notebook /content/25DLS304_NimishParmar.ipynb to html
[NbConvertApp] Writing 291949 bytes to /content/25DLS304_NimishParmar.html
