<a href="https://colab.research.google.com/github/Nimo160302/Deep_Learning_Codes/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#SOFTMAX FUNCTION
import numpy as np

In [3]:
def softmax(x):
  exp_x =  np.exp(x)
  return exp_x /np.sum(exp_x)

In [4]:
x = np.array([1.0, 2.0, 3.0])
print(softmax(x))

[0.09003057 0.24472847 0.66524096]


In [5]:
sum([0.09003057 ,0.24472847 ,0.66524096])

1.0

In [6]:
# Given these examples, classify each as AI, ML, or DL by writing print() statements.

examples = [

    "Self-driving car using CNNs",

    "Spam detection using Naive Bayes",

    "Expert system for medical diagnosis",

    "Face recognition using Siamese Networks",

    "Weather forecasting using linear regression"

]



# Use Python logic to classify them in your output.

In [7]:
print(f'{examples[0]}: DL problem')
print(f'{examples[1]}: ML problem')
print(f'{examples[2]}: AI problem')
print(f'{examples[3]}: DL problem')
print(f'{examples[4]}: ML problem')



Self-driving car using CNNs: DL problem
Spam detection using Naive Bayes: ML problem
Expert system for medical diagnosis: AI problem
Face recognition using Siamese Networks: DL problem
Weather forecasting using linear regression: ML problem


In [8]:
'''Generate a 5x5 random matrix with values between 0 and 1 using PyTorch.
Compute the mean, standard deviation, and sum of all elements using PyTorch operations.
Then, convert the tensor to a NumPy array and recompute these statistics using NumPy.'''


import torch

m  = torch.rand((5,5))
sum  =  torch.sum(m)
mean  = torch.mean(m)
sd  =  torch.std(m)

print(m)

print(f'\n sum of all elemet is : {sum},\n mean of all element is : {mean},\n standard deviation is {sd} ')




tensor([[0.3399, 0.9178, 0.6694, 0.2805, 0.8362],
        [0.2747, 0.9875, 0.4412, 0.6588, 0.5236],
        [0.7640, 0.6744, 0.1874, 0.2527, 0.5589],
        [0.8387, 0.5756, 0.7156, 0.8304, 0.9563],
        [0.5943, 0.1937, 0.4543, 0.9292, 0.7820]])

 sum of all elemet is : 15.237298011779785,
 mean of all element is : 0.6094919443130493,
 standard deviation is 0.2519480586051941 


In [9]:
n = np.array(m)
sum  = np.sum(n)
mean = np.mean(n)
sd = np.std(n)

print(n)

print(type(n))

print(f'\n sum of all elemet is : {sum},\n mean of all element is : {mean},\n standard deviation is {sd} ')


[[0.33991873 0.9178344  0.6694389  0.2805208  0.83624256]
 [0.27467722 0.9874868  0.4412474  0.65879846 0.52364016]
 [0.76403904 0.67440575 0.18736547 0.25265962 0.55892843]
 [0.838688   0.5755901  0.7155539  0.8304096  0.95631975]
 [0.59426725 0.19371063 0.4542873  0.92924476 0.78202474]]
<class 'numpy.ndarray'>

 sum of all elemet is : 15.237298965454102,
 mean of all element is : 0.6094919443130493,
 standard deviation is 0.2468576580286026 


In [1]:
# !sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic
# !jupyter nbconvert --to pdf /Assignment1.ipynb